/**
 * Atlas Runtime Governance Documentation
 */

module.exports = {
  docs: [
    "intro",

    {
      type: "category",
      label: "Foundation",
      link: {
        type: "generated-index",
        title: "Foundation",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "foundation",
        },
      ],
    },

    {
      type: "category",
      label: "Product Portfolio",
      link: {
        type: "generated-index",
        title: "Product Portfoli",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "products",
        },
      ],
    },

    {
      type: "category",
      label: "Platform",
      link: {
        type: "generated-index",
        title: "Platform",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "platform",
        },
      ],
    },

    {
      type: "category",
      label: "Deployment",
      link: {
        type: "generated-index",
        title: "Deployment",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "deployment",
        },
      ],
    },

    {
      type: "category",
      label: "Resource",
      link: {
        type: "generated-index",
        title: "Resource",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
    },
  ],
};
